version: '3.9'

services:
  nginx:
    ports:
      - "443:443"
    hostname: localhost
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - project
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - project
    env_file:
      - .env
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - project
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always

networks:
  project:
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/narguss/Desktop/test/achane-l/data/wordpress
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/narguss/Desktop/test/achane-l/data/database